image:
  - Visual Studio 2019
  - Ubuntu
install:
  - cmd: set QTDIR=C:\Qt\5.15\mingw81_32
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw810_32\bin;%PATH%;
  - sh: export PATH="$HOME/Qt/5.15.2/gcc_64/bin:$PATH"
build_script:
  - qmake BluePassServer.pro
  - cmd: mingw32-make
  - sh: make -j 4
after_build:
  - cmd: windeployqt release/BluePassServer.exe
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - cmd: mv release bluepass-server-win32
  - sh: mv release bluepass-server-linux
artifacts:
  - path: bluepass-server-win32
    type: zip
  - path: bluepass-server-linux
    type: zip

