image:
  - Ubuntu1604
  - Visual Studio 2019
install:
  - git submodule update --init --recursive
  - cmd: set QTDIR=C:\Qt\5.15\mingw81_32
  - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw810_32\bin;%PATH%;
  - sh: export DEBIAN_FRONTEND=noninteractive
  - sh: ./ci/install-qt-dependencies.sh
  - sh: ./ci/install-linuxdeployqt.sh $HOME/bin
  - sh: export QTDIR="$HOME/Qt/5.15.2/gcc_64"
  - sh: export PATH="$QTDIR/bin:$HOME/bin:$PATH"
build_script:
  - cmd: cmake -G "Ninja" -DQt5_DIR=%QTDIR%\lib\Qt5 .
  - sh: cmake -G "Ninja" -DQt5_DIR=$QTDIR/lib/cmake/Qt5 .
  - ninja
after_build:
  - cmd: mkdir bluepass-server-win32
  - cmd: cp BluePassServer.exe bluepass-server-win32/
  - cmd: windeployqt bluepass-server-win32/BluePassServer.exe
  - sh: mkdir bluepass-server-linux
  - sh: cp BluePassServer bluepass-server-linux/
  - sh: VERSION=${APPVEYOR_REPO_TAG_NAME} ./ci/package-appimage-linux.sh
artifacts:
  - path: bluepass-server-win32
    type: zip
  - path: bluepass-server-linux
    type: zip
  - path: Bluepass_Server-*.AppImage
deploy:
  description: bluepass-server release $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: +4g1P7zwdrIxOI+fYb8+SVZXUDnxk1v9Aig1uMzCBtcw/L0rp+qCyfJHNrSwyTZp
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
