image: Visual Studio 2019
install:
  - set QTDIR=C:\Qt\5.15\mingw81_32
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw810_32\bin;%PATH%;
build_script:
  - qmake BluePassServer.pro
  - mingw32-make
after_build:
  - windeployqt release/BluePassServer.exe
  - rm release/*.o
  - rm release/*.cpp
  - rm release/*.h
  - mv release bluepass-server
artifacts:
  - path: bluepass-server
    type: zip

